"""
    tsdTransform matchies metric names coming out of the bucky sever queue
    and changes the metric name sent to opentsdb.
"""

tsdTransform = {
    "cpu.0.idle" : { "name" : "cpu.idle", "tags" : "cpu=0 command=collectd" },
    "cpu.0.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=0 command=collectd" },
    "cpu.0.nice" : { "name" : "cpu.nice", "tags" : "cpu=0 command=collectd" },
    "cpu.0.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=0 command=collectd" },
    "cpu.0.steal" : { "name" : "cpu.steal", "tags" : "cpu=0 command=collectd" },
    "cpu.0.system" : { "name" : "cpu.system", "tags" : "cpu=0 command=collectd" },
    "cpu.0.user" : { "name" : "cpu.user", "tags" : "cpu=0 command=collectd" },
    "cpu.0.wait" : { "name" : "cpu.wait", "tags" : "cpu=0 command=collectd" },
    "cpu.1.idle" : { "name" : "cpu.idle", "tags" : "cpu=1 command=collectd" },
    "cpu.1.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=1 command=collectd" },
    "cpu.1.nice" : { "name" : "cpu.nice", "tags" : "cpu=1 command=collectd" },
    "cpu.1.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=1 command=collectd" },
    "cpu.1.steal" : { "name" : "cpu.steal", "tags" : "cpu=1 command=collectd" },
    "cpu.1.system" : { "name" : "cpu.system", "tags" : "cpu=1 command=collectd" },
    "cpu.1.user" : { "name" : "cpu.user", "tags" : "cpu=1 command=collectd" },
    "cpu.1.wait" : { "name" : "cpu.wait", "tags" : "cpu=1 command=collectd" },
    "cpu.2.idle" : { "name" : "cpu.idle", "tags" : "cpu=2 command=collectd" },
    "cpu.2.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=2 command=collectd" },
    "cpu.2.nice" : { "name" : "cpu.nice", "tags" : "cpu=2 command=collectd" },
    "cpu.2.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=2 command=collectd" },
    "cpu.2.steal" : { "name" : "cpu.steal", "tags" : "cpu=2 command=collectd" },
    "cpu.2.system" : { "name" : "cpu.system", "tags" : "cpu=2 command=collectd" },
    "cpu.2.user" : { "name" : "cpu.user", "tags" : "cpu=2 command=collectd" },
    "cpu.2.wait" : { "name" : "cpu.wait", "tags" : "cpu=2 command=collectd" },
    "cpu.3.idle" : { "name" : "cpu.idle", "tags" : "cpu=3 command=collectd" },
    "cpu.3.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=3 command=collectd" },
    "cpu.3.nice" : { "name" : "cpu.nice", "tags" : "cpu=3 command=collectd" },
    "cpu.3.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=3 command=collectd" },
    "cpu.3.steal" : { "name" : "cpu.steal", "tags" : "cpu=3 command=collectd" },
    "cpu.3.system" : { "name" : "cpu.system", "tags" : "cpu=3 command=collectd" },
    "cpu.3.user" : { "name" : "cpu.user", "tags" : "cpu=3 command=collectd" },
    "cpu.3.wait" : { "name" : "cpu.wait", "tags" : "cpu=3 command=collectd" },
    "cpu.4.idle" : { "name" : "cpu.idle", "tags" : "cpu=4 command=collectd" },
    "cpu.4.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=4 command=collectd" },
    "cpu.4.nice" : { "name" : "cpu.nice", "tags" : "cpu=4 command=collectd" },
    "cpu.4.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=4 command=collectd" },
    "cpu.4.steal" : { "name" : "cpu.steal", "tags" : "cpu=4 command=collectd" },
    "cpu.4.system" : { "name" : "cpu.system", "tags" : "cpu=4 command=collectd" },
    "cpu.4.user" : { "name" : "cpu.user", "tags" : "cpu=4 command=collectd" },
    "cpu.4.wait" : { "name" : "cpu.wait", "tags" : "cpu=4 command=collectd" },
    "cpu.5.idle" : { "name" : "cpu.idle", "tags" : "cpu=5 command=collectd" },
    "cpu.5.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=5 command=collectd" },
    "cpu.5.nice" : { "name" : "cpu.nice", "tags" : "cpu=5 command=collectd" },
    "cpu.5.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=5 command=collectd" },
    "cpu.5.steal" : { "name" : "cpu.steal", "tags" : "cpu=5 command=collectd" },
    "cpu.5.system" : { "name" : "cpu.system", "tags" : "cpu=5 command=collectd" },
    "cpu.5.user" : { "name" : "cpu.user", "tags" : "cpu=5 command=collectd" },
    "cpu.5.wait" : { "name" : "cpu.wait", "tags" : "cpu=5 command=collectd" },
    "cpu.6.idle" : { "name" : "cpu.idle", "tags" : "cpu=6 command=collectd" },
    "cpu.6.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=6 command=collectd" },
    "cpu.6.nice" : { "name" : "cpu.nice", "tags" : "cpu=6 command=collectd" },
    "cpu.6.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=6 command=collectd" },
    "cpu.6.steal" : { "name" : "cpu.steal", "tags" : "cpu=6 command=collectd" },
    "cpu.6.system" : { "name" : "cpu.system", "tags" : "cpu=6 command=collectd" },
    "cpu.6.user" : { "name" : "cpu.user", "tags" : "cpu=6 command=collectd" },
    "cpu.6.wait" : { "name" : "cpu.wait", "tags" : "cpu=6 command=collectd" },
    "cpu.7.idle" : { "name" : "cpu.idle", "tags" : "cpu=7 command=collectd" },
    "cpu.7.interrupt" : { "name" : "cpu.interrupt", "tags" : "cpu=7 command=collectd" },
    "cpu.7.nice" : { "name" : "cpu.nice", "tags" : "cpu=7 command=collectd" },
    "cpu.7.softirq" : { "name" : "cpu.softirq", "tags" : "cpu=7 command=collectd" },
    "cpu.7.steal" : { "name" : "cpu.steal", "tags" : "cpu=7 command=collectd" },
    "cpu.7.system" : { "name" : "cpu.system", "tags" : "cpu=7 command=collectd" },
    "cpu.7.user" : { "name" : "cpu.user", "tags" : "cpu=7 command=collectd" },
    "cpu.7.wait" : { "name" : "cpu.wait", "tags" : "cpu=7 command=collectd" },
    "load.shortterm" : { "name" : "load.shortterm", "tags" : "command=collectd" },
    "load.midterm" : { "name" : "load.midterm", "tags" : "command=collectd" },
    "load.longterm" : { "name" : "load.longterm", "tags" : "command=collectd" },
    "interface.eth0.if_errors.rx" : { "name" : "if.errors.rx", "tags" : "interface=eth0 command=collectd" },
    "interface.eth0.if_errors.tx" : { "name" : "if.errors.tx", "tags" : "interface=eth0 command=collectd" },
    "interface.eth0.if_octets.rx" : { "name" : "if.octets.rx", "tags" : "interface=eth0 command=collectd" },
    "interface.eth0.if_octets.tx" : { "name" : "if.octets.tx", "tags" : "interface=eth0 command=collectd" },
    "interface.eth0.if_packets.rx" : { "name" : "if.packets.rx", "tags" : "interface=eth0 command=collectd" },
    "interface.eth0.if_packets.tx" : { "name" : "if.packets.tx", "tags" : "interface=eth0 command=collectd" },
    "memory.buffered" : { "name" : "memory.buffered", "tags" : "command=collectd" },
    "memory.cached" : { "name" : "memory.cached", "tags" : "command=collectd" },
    "memory.free" : { "name" : "memory.free", "tags" : "command=collectd" },
    "memory.used" : { "name" : "memory.used", "tags" : "command=collectd" },
    "processes.fork_rate" : { "name" : "processes.fork_rate", "tags" : "command=collectd" },
    "processes.ps_state.blocked" : { "name" : "processes.blocked", "tags" : "command=collectd" },
    "processes.ps_state.paging" : { "name" : "processes.paging", "tags" : "command=collectd" },
    "processes.ps_state.running" : { "name" : "processes.running", "tags" : "command=collectd" },
    "processes.ps_state.sleeping" : { "name" : "processes.sleeping", "tags" : "command=collectd" },
    "processes.ps_state.stopped" : { "name" : "processes.stopped", "tags" : "command=collectd" },
    "processes.ps_state.zombies" : { "name" : "processes.zombies", "tags" : "command=collectd" },
}
